/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class target_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public int x_pix;
    public int y_pix;
 
    public target_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9ee8c1fc5df73927L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.target_t.class))
            return 0L;
 
        classes.add(lcmtypes.target_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.x_pix); 
 
        outs.writeInt(this.y_pix); 
 
    }
 
    public target_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public target_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.target_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.target_t o = new lcmtypes.target_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.x_pix = ins.readInt();
 
        this.y_pix = ins.readInt();
 
    }
 
    public lcmtypes.target_t copy()
    {
        lcmtypes.target_t outobj = new lcmtypes.target_t();
        outobj.timestamp = this.timestamp;
 
        outobj.x_pix = this.x_pix;
 
        outobj.y_pix = this.y_pix;
 
        return outobj;
    }
 
}

