/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class drive_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public int front_motor;
    public int back_motor;
    public int right_motor;
    public int left_motor;
 
    public drive_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa32fa1c39f0affd0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.drive_t.class))
            return 0L;
 
        classes.add(lcmtypes.drive_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.front_motor); 
 
        outs.writeInt(this.back_motor); 
 
        outs.writeInt(this.right_motor); 
 
        outs.writeInt(this.left_motor); 
 
    }
 
    public drive_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public drive_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.drive_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.drive_t o = new lcmtypes.drive_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.front_motor = ins.readInt();
 
        this.back_motor = ins.readInt();
 
        this.right_motor = ins.readInt();
 
        this.left_motor = ins.readInt();
 
    }
 
    public lcmtypes.drive_t copy()
    {
        lcmtypes.drive_t outobj = new lcmtypes.drive_t();
        outobj.timestamp = this.timestamp;
 
        outobj.front_motor = this.front_motor;
 
        outobj.back_motor = this.back_motor;
 
        outobj.right_motor = this.right_motor;
 
        outobj.left_motor = this.left_motor;
 
        return outobj;
    }
 
}

